name: Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar o python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar o poetry 
        uses: pip install poetry

      - name: Entrando na pasta
        uses: cd fast_zero

      - name: Instalar o as dependÃªncias 
        uses: poetry install
